package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

/**
 * Importes generated by hbm2java
 */
public class Importes implements java.io.Serializable {

	private ImportesId id;

	public Importes() {
	}

	public Importes(ImportesId id) {
		this.id = id;
	}

	public ImportesId getId() {
		return this.id;
	}

	public void setId(ImportesId id) {
		this.id = id;
	}

}
