package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProveedoresNew generated by hbm2java
 */
public class ProveedoresNew implements java.io.Serializable {

	private Integer id;
	private String empresa;
	private String contacto;
	private Set productosNews = new HashSet(0);

	public ProveedoresNew() {
	}

	public ProveedoresNew(String empresa) {
		this.empresa = empresa;
	}

	public ProveedoresNew(String empresa, String contacto, Set productosNews) {
		this.empresa = empresa;
		this.contacto = contacto;
		this.productosNews = productosNews;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public Set getProductosNews() {
		return this.productosNews;
	}

	public void setProductosNews(Set productosNews) {
		this.productosNews = productosNews;
	}

}
