package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

/**
 * Totales generated by hbm2java
 */
public class Totales implements java.io.Serializable {

	private TotalesId id;

	public Totales() {
	}

	public Totales(TotalesId id) {
		this.id = id;
	}

	public TotalesId getId() {
		return this.id;
	}

	public void setId(TotalesId id) {
		this.id = id;
	}

}
