package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

/**
 * TotalesMensuales generated by hbm2java
 */
public class TotalesMensuales implements java.io.Serializable {

	private TotalesMensualesId id;

	public TotalesMensuales() {
	}

	public TotalesMensuales(TotalesMensualesId id) {
		this.id = id;
	}

	public TotalesMensualesId getId() {
		return this.id;
	}

	public void setId(TotalesMensualesId id) {
		this.id = id;
	}

}
