package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

/**
 * VEmpleados1 generated by hbm2java
 */
public class VEmpleados1 implements java.io.Serializable {

	private VEmpleados1Id id;

	public VEmpleados1() {
	}

	public VEmpleados1(VEmpleados1Id id) {
		this.id = id;
	}

	public VEmpleados1Id getId() {
		return this.id;
	}

	public void setId(VEmpleados1Id id) {
		this.id = id;
	}

}
