package models;
// Generated 9 dic 2022 9:21:41 by Hibernate Tools 5.5.9.Final

/**
 * VNueva generated by hbm2java
 */
public class VNueva implements java.io.Serializable {

	private VNuevaId id;

	public VNueva() {
	}

	public VNueva(VNuevaId id) {
		this.id = id;
	}

	public VNuevaId getId() {
		return this.id;
	}

	public void setId(VNuevaId id) {
		this.id = id;
	}

}
