package models;
// Generated 13 ene 2023 9:28:56 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Concesionario generated by hbm2java
 */
public class Concesionario implements java.io.Serializable {

	private int id;
	private String nombre;
	private String direccion;
	private String contacto;
	private Set vehiculos = new HashSet(0);

	public Concesionario() {
	}

	public Concesionario(int id) {
		this.id = id;
	}

	public Concesionario(int id, String nombre, String direccion, String contacto, Set vehiculos) {
		this.id = id;
		this.nombre = nombre;
		this.direccion = direccion;
		this.contacto = contacto;
		this.vehiculos = vehiculos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
