package models;
// Generated 13 ene 2023 9:28:56 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico implements java.io.Serializable {

	private int id;
	private Integer codUsuario;
	private String especialidad;
	private Boolean esJefe;
	private Set reparas = new HashSet(0);

	public Mecanico() {
	}

	public Mecanico(int id) {
		this.id = id;
	}

	public Mecanico(int id, Integer codUsuario, String especialidad, Boolean esJefe, Set reparas) {
		this.id = id;
		this.codUsuario = codUsuario;
		this.especialidad = especialidad;
		this.esJefe = esJefe;
		this.reparas = reparas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(Integer codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Boolean getEsJefe() {
		return this.esJefe;
	}

	public void setEsJefe(Boolean esJefe) {
		this.esJefe = esJefe;
	}

	public Set getReparas() {
		return this.reparas;
	}

	public void setReparas(Set reparas) {
		this.reparas = reparas;
	}

}
