package models;
// Generated 25 ene 2023 9:47:57 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mecanico generated by hbm2java
 */
public class Mecanico implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private String especialidad;
	private Boolean esJefe;
	private Set reparas = new HashSet(0);

	public Mecanico() {
	}

	public Mecanico(Usuario usuario, String especialidad, Boolean esJefe, Set reparas) {
		this.usuario = usuario;
		this.especialidad = especialidad;
		this.esJefe = esJefe;
		this.reparas = reparas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Boolean getEsJefe() {
		return this.esJefe;
	}

	public void setEsJefe(Boolean esJefe) {
		this.esJefe = esJefe;
	}

	public Set getReparas() {
		return this.reparas;
	}

	public void setReparas(Set reparas) {
		this.reparas = reparas;
	}

}
