package models;
// Generated 25 ene 2023 9:47:57 by Hibernate Tools 5.5.9.Final

import java.util.Date;

/**
 * Proposicion generated by hbm2java
 */
public class Proposicion implements java.io.Serializable {

	private ProposicionId id;
	private Cliente cliente;
	private Vehiculo vehiculo;
	private Venta venta;
	private Double precioPropuesto;
	private Date fechaValidez;
	private Boolean aceptada;

	public Proposicion() {
	}

	public Proposicion(ProposicionId id, Cliente cliente, Vehiculo vehiculo, Venta venta) {
		this.id = id;
		this.cliente = cliente;
		this.vehiculo = vehiculo;
		this.venta = venta;
	}

	public Proposicion(ProposicionId id, Cliente cliente, Vehiculo vehiculo, Venta venta, Double precioPropuesto,
			Date fechaValidez, Boolean aceptada) {
		this.id = id;
		this.cliente = cliente;
		this.vehiculo = vehiculo;
		this.venta = venta;
		this.precioPropuesto = precioPropuesto;
		this.fechaValidez = fechaValidez;
		this.aceptada = aceptada;
	}

	public ProposicionId getId() {
		return this.id;
	}

	public void setId(ProposicionId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	public Double getPrecioPropuesto() {
		return this.precioPropuesto;
	}

	public void setPrecioPropuesto(Double precioPropuesto) {
		this.precioPropuesto = precioPropuesto;
	}

	public Date getFechaValidez() {
		return this.fechaValidez;
	}

	public void setFechaValidez(Date fechaValidez) {
		this.fechaValidez = fechaValidez;
	}

	public Boolean getAceptada() {
		return this.aceptada;
	}

	public void setAceptada(Boolean aceptada) {
		this.aceptada = aceptada;
	}

}
