package models;
// Generated 13 ene 2023 9:28:56 by Hibernate Tools 5.5.9.Final

import java.util.Date;

/**
 * Registroventas generated by hbm2java
 */
public class Registroventas implements java.io.Serializable {

	private int id;
	private Vehiculo vehiculo;
	private Venta venta;
	private Date fechaVenta;
	private Double beneficio;

	public Registroventas() {
	}

	public Registroventas(int id) {
		this.id = id;
	}

	public Registroventas(int id, Vehiculo vehiculo, Venta venta, Date fechaVenta, Double beneficio) {
		this.id = id;
		this.vehiculo = vehiculo;
		this.venta = venta;
		this.fechaVenta = fechaVenta;
		this.beneficio = beneficio;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public Double getBeneficio() {
		return this.beneficio;
	}

	public void setBeneficio(Double beneficio) {
		this.beneficio = beneficio;
	}

}
