package models;
// Generated 25 ene 2023 9:47:57 by Hibernate Tools 5.5.9.Final

/**
 * ReparaId generated by hbm2java
 */
public class ReparaId implements java.io.Serializable {

	private int idMecanico;
	private int idVehiculo;

	public ReparaId() {
	}

	public ReparaId(int idMecanico, int idVehiculo) {
		this.idMecanico = idMecanico;
		this.idVehiculo = idVehiculo;
	}

	public int getIdMecanico() {
		return this.idMecanico;
	}

	public void setIdMecanico(int idMecanico) {
		this.idMecanico = idMecanico;
	}

	public int getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReparaId))
			return false;
		ReparaId castOther = (ReparaId) other;

		return (this.getIdMecanico() == castOther.getIdMecanico())
				&& (this.getIdVehiculo() == castOther.getIdVehiculo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMecanico();
		result = 37 * result + this.getIdVehiculo();
		return result;
	}

}
