package models;
// Generated 13 ene 2023 9:28:56 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private String nombre;
	private String apellidos;
	private String nif;
	private String correo;
	private String telefono;
	private String contrasena;
	private Set ventas = new HashSet(0);
	private Set jefes = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int id) {
		this.id = id;
	}

	public Usuario(int id, String nombre, String apellidos, String nif, String correo, String telefono,
			String contrasena, Set ventas, Set jefes) {
		this.id = id;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nif = nif;
		this.correo = correo;
		this.telefono = telefono;
		this.contrasena = contrasena;
		this.ventas = ventas;
		this.jefes = jefes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public Set getVentas() {
		return this.ventas;
	}

	public void setVentas(Set ventas) {
		this.ventas = ventas;
	}

	public Set getJefes() {
		return this.jefes;
	}

	public void setJefes(Set jefes) {
		this.jefes = jefes;
	}

}
