package models;
// Generated 25 ene 2023 9:47:57 by Hibernate Tools 5.5.9.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import hibernate.persistence.models.AbstractEntity;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo extends AbstractEntity implements java.io.Serializable {

	private int id;
	private Concesionario concesionario;
	private String marca;
	private String modelo;
	private String tipo;
	private String color;
	private Integer potencia;
	private Double precio;
	private Boolean disponible;
	private Date fechaEntradaConcesionario;
	private Set proposicions = new HashSet(0);
	private Set registroventases = new HashSet(0);
	private Set clientes = new HashSet(0);
	private Set reparas = new HashSet(0);

	public Vehiculo() {
	}

	public Vehiculo(String tipo) {
		this.tipo = tipo;
	}

	public Vehiculo(Concesionario concesionario, String marca, String modelo, String tipo, String color,
			Integer potencia, Double precio, Boolean disponible, Date fechaEntradaConcesionario, Set proposicions,
			Set registroventases, Set clientes, Set reparas) {
		this.concesionario = concesionario;
		this.marca = marca;
		this.modelo = modelo;
		this.tipo = tipo;
		this.color = color;
		this.potencia = potencia;
		this.precio = precio;
		this.disponible = disponible;
		this.fechaEntradaConcesionario = fechaEntradaConcesionario;
		this.proposicions = proposicions;
		this.registroventases = registroventases;
		this.clientes = clientes;
		this.reparas = reparas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Concesionario getConcesionario() {
		return this.concesionario;
	}

	public void setConcesionario(Concesionario concesionario) {
		this.concesionario = concesionario;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Integer getPotencia() {
		return this.potencia;
	}

	public void setPotencia(Integer potencia) {
		this.potencia = potencia;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	public Boolean getDisponible() {
		return this.disponible;
	}

	public void setDisponible(Boolean disponible) {
		this.disponible = disponible;
	}

	public Date getFechaEntradaConcesionario() {
		return this.fechaEntradaConcesionario;
	}

	public void setFechaEntradaConcesionario(Date fechaEntradaConcesionario) {
		this.fechaEntradaConcesionario = fechaEntradaConcesionario;
	}
	
	public Set getProposicions() {
		return this.proposicions;
	}

	public void setProposicions(Set proposicions) {
		this.proposicions = proposicions;
	}

	public Set getRegistroventases() {
		return this.registroventases;
	}

	public void setRegistroventases(Set registroventases) {
		this.registroventases = registroventases;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

	public Set getReparas() {
		return this.reparas;
	}

	public void setReparas(Set reparas) {
		this.reparas = reparas;
	}

}
