package models;
// Generated 13 ene 2023 9:28:56 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Set proposicions = new HashSet(0);
	private Set registroventases = new HashSet(0);

	public Venta() {
	}

	public Venta(int id) {
		this.id = id;
	}

	public Venta(int id, Usuario usuario, Set proposicions, Set registroventases) {
		this.id = id;
		this.usuario = usuario;
		this.proposicions = proposicions;
		this.registroventases = registroventases;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Set getProposicions() {
		return this.proposicions;
	}

	public void setProposicions(Set proposicions) {
		this.proposicions = proposicions;
	}

	public Set getRegistroventases() {
		return this.registroventases;
	}

	public void setRegistroventases(Set registroventases) {
		this.registroventases = registroventases;
	}

}
